### ISSUE TITLE
npm Dependency Installation Error

### ISSUE THREAD

**Issue by sn1f3rt** [bchiang7/v2#1]
Hello Brittany,

I'm facing an error during the installation of the requisite NodeJS packages while installation via npm. Here's the error log -

```
2921 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"        
2922 verbose node v12.16.1                                        
2923 verbose npm  v6.13.4                                         
2924 error code ETARGET                                           
2925 error notarget No matching version found for eslint-config-st
arry@2.0.1.                                                       
2926 error notarget In most cases you or one of your dependencies 
are requesting                                                    
2926 error notarget a package version that doesn't exist.         
2926 error notarget                                               
2926 error notarget It was specified as a dependency of 'public_ht
ml'
```

Could you please tell me an alternative, or suggest a fix if possible?

Regards,
S Bhattacharyya.

**Comment by AmbiTyga** [comment]
Go to the package.json and replace the 

```
"eslint-config-starry":"3.0.1",
"eslint-plugin-starry":"3.0.1"
```
under `"devDependencies"` with
```
"@starryinternet/eslint-config-starry": "~9.2.0",
"@starryinternet/eslint-plugin-starry": "~7.3.8",
```

**Comment by sn1f3rt** [comment]
Hmm, well I'd done that a while ago but still, you're sure to get another error while doing `gulp build` and hence I'd given up and adopted a basic HTML template. You can check my portfolio here - https://sohamb03.me

It's basically the Freelancer theme from StartBootstrap, but heavily modified to suit my needs. :-) 

Time to close this.
